name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build project
      - name: Build project
        run: npm run build

      # Step 5: Create executable
      - name: Create executable
        run: npm run make:portable

      # Step 6: Debug - Verify that the artifact exists
      - name: Verify artifact
        run: |
          echo "Listing contents of dist directory:"
          dir dist
          if not exist "dist\SpeechToTextApp.exe" (
            echo "Error: dist\SpeechToTextApp.exe does not exist!"
            exit 1
          )

      # Step 7: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: speech-to-text-app
          path: dist/SpeechToTextApp.exe
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      # Step 1: Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: speech-to-text-app

      # Step 2: Debug - Verify downloaded artifact
      - name: Verify downloaded artifact
        run: |
          echo "Checking for downloaded file:"
          ls -la
          if [ ! -f "SpeechToTextApp.exe" ]; then
            echo "Error: SpeechToTextApp.exe not found!"
            exit 1
          fi

      # Step 3: Create Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: SpeechToTextApp.exe
