name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '16'
  ARTIFACT_NAME: 'speech-to-text-app'
  OUTPUT_FILE: 'SpeechToTextApp.exe'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-

      # Step 3: Cache Electron and NSIS binaries
      - name: Cache Electron and NSIS binaries
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ env.NODE_VERSION }}-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-${{ env.NODE_VERSION }}-

      # Step 4: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json # صراحتاً به package-lock.json اشاره می‌کند

      # Step 5: Verify package-lock.json
      - name: Verify package-lock.json
        shell: bash
        run: |
          if [ ! -f "package-lock.json" ]; then
            echo "Error: package-lock.json not found! Generating one..."
            npm install
            git diff --quiet package-lock.json || git add package-lock.json && git commit -m "Generate package-lock.json"
          fi

      # Step 6: Install dependencies
      - name: Install dependencies
        shell: bash
        run: npm ci
        timeout-minutes: 8

      # Step 7: Build project
      - name: Build project
        shell: bash
        run: npm run build
        env:
          NODE_ENV: production
        timeout-minutes: 5

      # Step 8: Debug - Verify build output
      - name: Verify build output
        shell: cmd
        run: |
          echo "Listing contents of dist directory after build:"
          dir dist
          if not exist "dist\*.js" (
            echo "Error: No JavaScript files found in dist! Build failed."
            exit 1
          )

      # Step 9: Create executable
      - name: Create executable
        shell: cmd
        run: |
          echo "Running electron-builder..."
          npm run make:portable -- --no-sign
          echo "Listing contents of dist directory after make:"
          dir dist
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
          DEBUG: electron-builder*
        timeout-minutes: 10

      # Step 10: Verify artifact
      - name: Verify artifact
        shell: cmd
        run: |
          echo "Listing contents of dist directory:"
          dir dist
          if not exist "dist\${{ env.OUTPUT_FILE }}" (
            echo "Error: dist\${{ env.OUTPUT_FILE }} does not exist!"
            exit 1
          )

      # Step 11: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}-windows
          path: dist/${{ env.OUTPUT_FILE }}
          if-no-files-found: error
          retention-days: 5
